# Generated by Django 3.0.6 on 2020-05-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('article_content', models.TextField(verbose_name='文章内容')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('edited_date', models.DateTimeField(verbose_name='编辑日期')),
                ('liked_times', models.IntegerField(default=0, verbose_name='被点赞次数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='文章标签')),
                ('related_article_nums', models.IntegerField(default=1, verbose_name='相关文章数量')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='用户昵称')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('region', models.CharField(max_length=50, verbose_name='所属地区')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='电子邮箱')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
            ],
            options={
                'verbose_name': '用户',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_user', models.CharField(max_length=50)),
                ('comment_content', models.TextField()),
                ('liked_times', models.IntegerField(default=0)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_backend.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_backend.User', verbose_name='文章作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog_backend.Tag', verbose_name='文章标签'),
        ),
    ]
