# Generated by Django 3.0.6 on 2020-05-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('文章标题', models.CharField(max_length=100)),
                ('文章内容', models.TextField()),
                ('创建日期', models.DateTimeField(auto_now_add=True)),
                ('上次修改日期', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('用户昵称', models.CharField(default='user5264', max_length=50)),
                ('用户名', models.CharField(max_length=50, unique=True)),
                ('用户密码（加密后）', models.CharField(max_length=50)),
                ('所在地区', models.CharField(max_length=50)),
                ('用户邮箱', models.EmailField(max_length=254, unique=True)),
                ('注册日期', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论内容', models.TextField()),
                ('评论时间', models.DateTimeField(auto_now_add=True)),
                ('被评论文章', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_backend.Article')),
                ('评论用户', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_backend.User')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='文章作者',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_backend.User'),
        ),
    ]
