# Generated by Django 3.0.6 on 2020-05-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0002_auto_20200510_0326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户'},
        ),
    ]
