# Generated by Django 3.0.6 on 2020-05-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0003_auto_20200510_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.CharField(max_length=50),
        ),
    ]
